### PR TITLE
Preprocess rework

### PR DESCRIPTION
**Pull request by myagues**
This is some rework of the preprocess routine:
- Single progress bar when generating features (uses Python's default multiprocessing)
- Compute statistics at the same time as preprocessing features
- I have left a `compute_statistics` function just in case someone needs it

Check out if you like the changes, or would like some other modifications.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@myagues thanks, LGTM. But need @azraelkuan review since he also has some modifications to support chinese dataset :D.

**Comment by myagues** [comment]
> btw, looking for ur PR to optimize reading tf.data :))

I'll retake the job soon :)

I need to provide some fixes here, because I realized this currently breaks `fastspeech_inference.ipynb`

**Comment by dathudeptrai** [comment]
@myagues i'm re-thinking about preprocessing. Maybe we just need save **Raw-feats** for simple. For norm feature we can compute it on the fly on data-loader since it's just norm so it still very fast and also user can ez to modify the norm function on data-loader :D.

**Comment by myagues** [comment]
This should work correctly now.

@azraelkuan and @crux153 I have changed the way dataset processor is loaded in preprocessing, similar to what was proposed in #105 (add `--dataset` argument and choose the corresponding processor), but if you think other changes would work better let me know.

**Comment by dathudeptrai** [comment]
@myagues thanks, the code look better now. @crux153 , @azraelkuan PTAL if you guys can adapt with this style of preprocessing. Everything LGTM.

**Comment by azraelkuan** [comment]
this also looks good to me！

**Comment by crux153** [comment]
Looks good to me too 👍

**Pull request merged**
