### PR TITLE
huggingface gradio web demo

### PR DESCRIPTION
**Pull request by AK391**
easy to use web demo on huggingface spaces using gradio

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@AK391 Many thanks, the app is great ! :D

**Comment by dathudeptrai** [comment]
@AK391 BTW, how can I contribute for this demo app ?. It would be great if there was a button for the selection of models. 

cc: @ZDisket

**Comment by AK391** [comment]
@dathudeptrai thanks for merging, the app is here https://huggingface.co/spaces/akhaliq/TensorFlowTTS/blob/main/app.py, I can add a dropdown list for selecting different models.

**Comment by dathudeptrai** [comment]
>  I can add a dropdown list for selecting different models.

That's great!. Because this repo has integrated with huggingfacehub so everything will be easy :D

**Comment by ZDisket** [comment]
@AK391 Hmm, this is very nice. All this using free inference API right? I'm interested in hosting my own.

**Pull request merged**
