### PR TITLE
🚀 📝 Add TFLite-convertible TFFastSpeech

### PR DESCRIPTION
**Pull request by jaeyoo**
This commit adds TFLite-convertible logics inside LengthRegulator.

This is tested with `tf-nightly`. 20200630 version. The quantized FastSpeech TFLite file can work with varied-length input & output.
Also,  we fixed the batch_size = 1 during inference. 
In addition, the real problem was the input tensor_spec mismatch inside of `tf.while_loop()`.
the 4th and 5th input tensors are growing (outputs, encoder_masks). this kind of dynamic size (not dynamic shape, please be careful of words. they are different) is not well recommended in TFLite converter. In this assumption, we removed the `tf.while_loop()` during inference as well.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@jaeyoo could not be more appreciated :D. Really nice trick, sice we tflite support batch-size 1 so we can simply remove tf.while_loop :)). Can you make the PR for notebook examples convert to tflite tacotron2 and fastspeech ?, i can do it if you don't have a time to do :D. BTW, What brings you here :)))

**Comment by jaeyoo** [comment]
@dathudeptrai I've already created colab notebooks for both models with google internal environment. So I suggest you not to do duplicated work. Let me open the PRs for notebooks next week after cleaning up the codes. Thanks!

**Comment by jaeyoo** [comment]
> @dathudeptrai I've already created colab notebooks for both models with google internal environment. So I suggest you not to do duplicated work. Let me open the PRs for notebooks next week after cleaning up the codes. Thanks!

I meant, will open the new PRs for notebooks after merging my two PRs. and FYI, this PR, fastspeech, doesn't depend on dynamic_decode(), so it can be merged now. Thanks.

**Comment by dathudeptrai** [comment]
@jaeyoo we can copy dynamic_decode to util folder and modify it so we don't really need wait for tf_addons updated it :)) it will take much time, i think =)). When tf_addons update, i can simply remove dynamic_decode from util folder and re-install newest tf_addons :)).

**Comment by manmay-nakhashi** [comment]
@jaeyoo even if input signature is [1, None] why second dim is [1,1] ? , is this a bug ? , should i report in tflite ? 
{'name': 'input_ids', 'index': 0, '**shape': array([1, 1], dtype=int32)**, 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'attention_mask', 'index': 1, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.bool_'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'speaker_ids', 'index': 2, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'speed_ratios', 'index': 3, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}

**Comment by dathudeptrai** [comment]
@manmay-nakhashi that ok :))). Don't care the shape infomation. Pls look 
```
 'shape_signature': array([ 1, -1], dtype=int32)
```

**-1** here is None :)) and dynamic.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai but when i am running inference it's saying it can't take multiple second dim ? 
ValueError: Cannot set tensor: Dimension mismatch. Got 2 but expected 1 for input 2.

**Comment by dathudeptrai** [comment]
@manmay-nakhashi can you use tflite-nightly ? . Dynamic shape have just supported recently. Or maybe this is an missmatch between mobile API and python API. It should run fine when deploy on real mobile :))).

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i an using tflite-nightly suggested version , i think it's mobile vs python API mismatch , i'll try it on mobile :+1:

**Comment by jaeyoo** [comment]
> @jaeyoo even if input signature is [1, None] why dim is [1,1] ? , is this a bug ? , should i report in tflite ?
> {'name': 'input_ids', 'index': 0, '**shape': array([1, 1], dtype=int32)**, 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'attention_mask', 'index': 1, 'shape': array([1, 1], dtype=int32), 'shape_signature': array([ 1, -1], dtype=int32), 'dtype': <class 'numpy.bool_'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'speaker_ids', 'index': 2, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.int32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}, {'name': 'speed_ratios', 'index': 3, 'shape': array([1], dtype=int32), 'shape_signature': array([1], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0), 'quantization_parameters': {'scales': array([], dtype=float32), 'zero_points': array([], dtype=int32), 'quantized_dimension': 0}, 'sparsity_parameters': {}}

No, it is intended. please give me some time to open a new PR including notebook file for inference with TFLite file. For short, we need to user `interpreter.resize_tensor_input()` for the `input_idx` tensor and then run `interpreter.allocate_tensors()`

**Comment by manmay-nakhashi** [comment]
@jaeyoo ok

**Pull request merged**
