### PR TITLE
add iOS example

### PR DESCRIPTION
**Pull request by kewlbear**
Thank you for your great project!
I've put together an example app for iOS.
Please review this pull request.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@kewlbear great work!, let me take a look and merge :D.

**Review by dathudeptrai — DISMISSED** [review]

**Comment by luan78zaoha** [comment]
@dathudeptrai @kewlbear  Look good! I suggest the model files could be removed, which are ~30MB in size.

**Comment by dathudeptrai** [comment]
@kewlbear can you remove the model files ?

**Comment by kewlbear** [comment]
Sure.

2021년 3월 18일 (목) 오후 6:37, dathudeptrai ***@***.***>님이 작성:

**Review by dathudeptrai — DISMISSED** [review]

**Review by dathudeptrai — APPROVED** [review]

**Comment by kewlbear** [comment]
Thanks! @dathudeptrai

**Pull request merged**
