### PR TITLE
Add FastSpeech with TFLite colab notebook file.

### PR DESCRIPTION
**Pull request by jaeyoo**
Please test this notebook file within your environment.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
Thanks, LGTM, merge now :D.

**Comment by manmay-nakhashi** [comment]
@jaeyoo using [tf.lite.Optimize.DEFAULT] increases inference time by a lot some how it is making it slower, inference time is increasing to 10x.

**Comment by dathudeptrai** [comment]
@manmay-nakhashi you mean on mobile device ? or in desktop ?

**Comment by manmay-nakhashi** [comment]
@dathudeptrai in desktop

**Comment by dathudeptrai** [comment]
@manmay-nakhashi yeah so it's understandable. The notebook convert to 8bit that tflite not yet optimize for x86 so it run very slow. Try it on ARM :)))

**Comment by manmay-nakhashi** [comment]
@dathudeptrai same optimization in melgan in increasing speed a lot on desktop

**Comment by dathudeptrai** [comment]
@manmay-nakhashi hi it doesn't make any sense if you run it on desktop, as far as i know, tflite now not yet optimize for Desktop, pls bring it into ARM structure (mobile devices, ...). For me FastSpeech run very fast on mobile device.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i am not running on desktop i am just testing on desktop for a quick sanity checks.

**Comment by dathudeptrai** [comment]
@manmay-nakhashi running on desktop is just to check the output :)).

**Comment by manmay-nakhashi** [comment]
> @manmay-nakhashi hi it doesn't make any sense if you run it on desktop, as far as i know, tflite now not yet optimize for Desktop, pls bring it into ARM structure (mobile devices, ...). For me FastSpeech run very fast on mobile device. I don't know the word **increase** in ur statement, the model size is 112mb on float32 so it's a same and you are runing it on desktop so the speed is normal with float32. **28mb** is int8, i run very slow on desktop.

@dathudeptrai  i ment it is back to 112 mb for float32. : ))

**Comment by manmay-nakhashi** [comment]
> @manmay-nakhashi running on desktop is just to check the output :)).

@dathudeptrai i think this resolves my doubt , about speed :+1:  :smile: :tada:

**Pull request merged**
