### PR TITLE
C++ inference base on tflite model

### PR DESCRIPTION
**Pull request by lr2582858**
- C++ Code of TTSFrontend (text2ids) and TTSBackend (Mel-generator and Vocoder)  are available;
- A demo of Mandarin TTS using tflite models, and the converted models and the builded tflite static library are available.

This example help developers run popular text-to-speech (TTS) models on mobile, embedded, and IoT devices.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@lr2582858 wow, thank you very much, great job! :D. Let us review ur PR now :D.

**Comment by dathudeptrai** [comment]
@lr2582858 a folder `lib` seems too big, can we somehow remove it from the repo (we can use git submodule or just add a README to tell a user copy the original repo or something simillar ?)

**Comment by lr2582858** [comment]
@dathudeptrai Thanks for your comments. The folder lib is really too big, I have delete it and provide a download link. Also, the relevant explanations have been added to README.

**Review by dathudeptrai — APPROVED** [review]

**Review by candlewill — APPROVED** [review]

**Review by ZDisket — APPROVED** [review]
Looks good.

**Comment by X-CCS** [comment]
@lr2582858  Hello author! Thank you very much for your work. I'd like to ask you a question:

+ In `main.cpp`, `const char* cmd = "python3 ../demo/text2ids.py`, which is a Python version of the text to `ids`, can be replaced by C++ code?

**Comment by lr2582858** [comment]
@X-CCS If English TTS, you can refer to [cppwin](https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/cppwin) . 
But if Chinese TTS, there is no open source code in c/c++ to use at present. 
- If just doing some experiments, you can build a Pinyin Dictionary of common Chinese characters. Or you can refer https://github.com/yinqiwen/cn2py and https://github.com/Shellbye/hanzi2pinyin, and an additional Pinyin format conversion is needed, like "dài" to "d ai4", to match baker_mapper.json.
- If it is commercial, Pinyin may be more complicated than designing and training a TTS model. It needs to solve many problems such as word segmentation (分词), polyphonic words（多音字）, phrase tone sandhi (词组的拼音变调, like "太阳 tai4yang2 -> tai4yang5" or "你好 ni3hao3 -> ni2hao3" ) and so on.

**Pull request merged**
