### PR TITLE
Add phonetic MFA for FastSpeech2

### PR DESCRIPTION
**Pull request by ZDisket**
This will add support for training phonetic FastSpeech2 without requiring durations from a teacher model by using MFA to extract them. It also fixes the LJSpeech processor so that it can take ARPA input, along with an input processor. Also `--pretrained `parameter to fine-tune FastSpeech2.
You can see my model here: https://drive.google.com/drive/folders/1wlv0sVsh9QHc9IE1pKf4-kg0i6pAI-yK?usp=sharing
And play with it at this notebook: https://colab.research.google.com/drive/1BIlkZ91Ov7KMYJsl_P2SVFcJ9nyFNaLT?usp=sharing
Also, I commit too much and have no idea what I'm doing.

### CODE REVIEW

**Comment by machineko** [comment]
@ZDisket use https://github.com/psf/black to fix formatting (u have mixed 2 spaces with 4 spaces in your fork).
Also you can use https://www.pylint.org/ to check python style guide (snake case vs camel case etc.) for example -> 
```python
def processtxtph:
    pass
trimdurlist = []
```
should be named
```python
def process_txt_ph:
    pass
trim_dur_list = []
```

**Comment by dathudeptrai** [comment]
@ZDisket thank for your contribution. I think ur contribution is still usefull since it's related with ur C++ code, we will merge ur C++ code asap, btw, what is ur full name ?

**Comment by ZDisket** [comment]
@dathudeptrai 
>btw, what is ur full name ?
Alejandro Miguel Velasquez.

**Comment by ZDisket** [comment]
@dathudeptrai Also, are you open to publishing my LJSpeech phonetic model in https://github.com/TensorSpeech/TensorFlowTTS/tree/master/examples/fastspeech2? I think its dictionary matches @machineko's implementation

**Comment by dathudeptrai** [comment]
@ZDisket yes, but let us finish abstract processor first, we should use vocab.txt file to load symbols to make sure inference works fine :D.

**Pull request closed without merging**
