### PR TITLE
🎐 Fix gan 2 steps

### PR DESCRIPTION
**Pull request by dathudeptrai**
We do not need 2 step training for gan-based model anymore :100:

### CODE REVIEW

**Review by machineko — APPROVED** [review]
LGFM

**Review by ZDisket — APPROVED** [review]
Looks good.

**Comment by dathudeptrai** [comment]
@ZDisket @machineko did you guys try to train with debug config to re-check this :))).

**Comment by ZDisket** [comment]
@dathudeptrai 
>did you guys try to train with debug config to re-check this :))).

I trained `hifigan.v1` with the discriminator set to start at 1000 steps and mixed precision for the generator on a small dataset. The training switches seamlessly with zero problems
`[train]:   0% 834/4000000 [04:21<256:02:15,  4.34it/s]`
then
`[train]:   0% 1064/4000000 [06:13<1444:12:35,  1.30s/it]
`

**Pull request closed without merging**
