### PR TITLE
Sort import turns

### PR DESCRIPTION
**Pull request by MokkeMeguru**
You should import sys and sys.path.append(".") before the import of example's folder.
see. https://github.com/TensorSpeech/TensorflowTTS/issues/93

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@MokkeMeguru hmm, weir, i use black and seems it automatically sort :(

**Comment by MokkeMeguru** [comment]
Wow... but 
```
import sys
sys.path.append(".")
```
this is first-order lines in all examples' codes.

**Comment by MokkeMeguru** [comment]
(black had not  been supported import sorting because this problem, but now may support it suddenly... . If this sort is becuase of black, black team did stupid updates.)

**Comment by MokkeMeguru** [comment]
@dathudeptrai 
Can you try my vs code settings
```json
{
  "[python]": {
    "editor.codeActionsOnSave": {
      "source.organizeImports": false
    }
  },
  "python.linting.enabled": true,
  "python.linting.pylintEnabled": false,
  "python.linting.lintOnSave": true,
  "python.linting.flake8Enabled": false,
  "editor.formatOnSave": true,
  "python.formatting.provider": "black"
}
```
This settings prevent import sorting, I think.

**Pull request merged**
