### PR TITLE
Add full TFLite pipeline for FastSpeech and MBMelgan

### PR DESCRIPTION
**Pull request by sujeendran**
I have added a notebook to convert mb-melgan also to tf-lite form and test full pipeline for TFLite inference. 
Note: This notebook uses FastSpeech.v3 and requires tf-nightly 2.4dev.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@sujeendran thanks :)), i also updated the fastspeech2 conversion on google colab, can you update ur notebook also to check the Quality of FastSpeech2 ?

**Comment by sujeendran** [comment]
@dathudeptrai Sure I will try it.

**Comment by dathudeptrai** [comment]
@sujeendran also don't forget to add the code to hear audio generated at the end of the notebook :)), i think float16 or float32 is ok but for int8 i think the performance will drop much :)).

**Comment by sujeendran** [comment]
Hi I have added FastSpeech2 TFLite also based on your updated notebook. Please check. 
BTW, i noticed the prepare input function in your notebook is missing the f0 and energy ratios fields. I had to add it in my notebook to get it working. I have added Audio() function to listen to audios generated.

**Comment by sujeendran** [comment]
@dathudeptrai In case you face trouble viewing the notebook here is the colab link for the same: https://colab.research.google.com/drive/1DTmxxhYy69UgVyPlfaTD85h_UZT9Qi25?usp=sharing

**Comment by dathudeptrai** [comment]
@sujeendran give me some times, i will merge soon

**Comment by manmay-nakhashi** [comment]
@dathudeptrai i can add streaming part in this notebook.

**Comment by dathudeptrai** [comment]
@manmay-nakhashi you can add streaming part on separate folder in examples dir. Maybe we should implement something like client/server :)). Also i think this streaming should add non-commercial license. At this time, anything about android app or server-side should licensed under non-commercial License rather than Apache2.0.

**Comment by manmay-nakhashi** [comment]
@dathudeptrai sure sounds good to me :)

**Comment by MegaPanchamZ** [comment]
> @dathudeptrai In case you face trouble viewing the notebook here is the colab link for the same: https://colab.research.google.com/drive/1DTmxxhYy69UgVyPlfaTD85h_UZT9Qi25?usp=sharing

Is the TFlite model quantized? Does that mean there are large amounts of latency? Hence the long runtimes.
If porting this to be (near) realtime what should the steps forward involve.

**Comment by dathudeptrai** [comment]
@MegaPanchamZ hi, FastSpeech2+Mb-melgan is already faster than real-time. And yes, the model converts to 8bit so the size reduces 4x times but because tflite optimize not yet optimize for x86 so the inference time will be very slow.

**Comment by OscarVanL** [comment]
FYI, you're missing a dependency
image

**Pull request closed without merging**
