### PR TITLE
📝 🚀 Add `inference_tflite()` in `TFTacotron2`

### PR DESCRIPTION
**Pull request by jaeyoo**
This commit adds TFLite-convertible inference function in `TFTacotron2`.
This depends on the new dynamic decoder here (https://github.com/tensorflow/addons/pull/1964)
Please DO NOT submit this change before `tensorflow_addons.seq2seq.dynamic_decode` is updated.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@jaeyoo thanks for ur great pull request. Did you check the whole TFTacotron2 can be convert to tflite or this is just dynamic_decode part and you think the other part is ok ?

**Comment by jaeyoo** [comment]
> @jaeyoo thanks for ur great pull request. Did you check the whole TFTacotron2 can be convert to tflite or this is just dynamic_decode part and you think the other part is ok ?

I've tested converting the whole `TFTacotron2` with `TFLiteConverter.from_keras_model()` but failed. It requires more restrictions. So I decided to convert `TFTacotron2.inference_tflite()` only with `TFLiteConverter.from_concrete_functions()` and it worked great well. This only affects the `dynamic_decode()`.

**Comment by dathudeptrai** [comment]
Nice ! I will test it. BTW, since you are a member of tflite so can you take a look at #75, fastspeech may more suitable to deploy on mobile devices. And as far as i know tflite now supported dynamic shape for 32 bit so i think if fastspeech can convert to tflite, this is really helpful on real deployment situation.

**Comment by jaeyoo** [comment]
> Nice ! I will test it. BTW, since you are a member of tflite so can you take a look at #75, fastspeech may more suitable to deploy on mobile devices. And as far as i know tflite now supported dynamic shape for 32 bit so i think if fastspeech can convert to tflite, this is really helpful on real deployment situation. @jaeyoo

Sure, please let me look at it.

**Comment by jaeyoo** [comment]
@dathudeptrai As you requested, we TFLite team could convert FastSpeech model as well. It was very hard to convert the model without any modification, we decided to change your model again, and push changes to your repo with this PR:

https://github.com/TensorSpeech/TensorflowTTS/pull/84

Thanks.

**Comment by dathudeptrai** [comment]
@jaeyoo thanks very much :))) again, just curious, **What brings you here** :D

**Comment by jaeyoo** [comment]
> @jaeyoo thanks very much :))) again, just curious, **What brings you here** :D, are u working on TTS ?

:) Sorry, I missed the question. This brings me here.

https://github.com/tensorflow/tensorflow/issues/40504

**Comment by dathudeptrai** [comment]
@jaeyoo but the man report the bug when convert to tffastspeech but here you pull request for tacotron2 :)) haha, anyway, i'm not sure if you know that what you did here :)), will change the game not only about TTS but also pytorch/tensorflow2 :))).

**Comment by jaeyoo** [comment]
PTAL

**Pull request merged**
