### PR TITLE
First commit of Android Demo

### PR DESCRIPTION
**Pull request by mapledxf**
### Android Demo

This is a simple Android demo which will load converted FastSpeech2 and Multi-Band MelGAN modules to synthesize audio.

### TO-DO:
* LJSpeechProcessor is not implemented in this demo.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@mapledxf is that finish ?, do you think you should add readme to show how to run/build the code ?

**Comment by manmay-nakhashi** [comment]
@mapledxf @dathudeptrai after fist commit i'll merge LJSpeechProcessor i have it implemented and i have a way to make this dynamic also.

**Comment by dathudeptrai** [comment]
@manmay-nakhashi the only thing before merge is that we need decide the license of this app, i suggest it is non-commercial license, what do you think ?

**Comment by manmay-nakhashi** [comment]
@dathudeptrai sounds good

**Comment by mapledxf** [comment]
@dathudeptrai It is completed. The LICENSE and some how-to have been added.

**Comment by dathudeptrai** [comment]
@mapledxf can you consider to change license to https://creativecommons.org/licenses/by-nc/3.0/ ?

**Comment by mapledxf** [comment]
@dathudeptrai do I put the license in the README?

**Comment by dathudeptrai** [comment]
@mapledxf yes, you just need add LICENSE on README by :

```
 The license use for this code is `CC BY-NC 3.0` (https://creativecommons.org/licenses/by-nc/3.0/)
```

**Comment by mapledxf** [comment]
@dathudeptrai done

**Comment by dathudeptrai** [comment]
@mapledxf thanks

**Pull request merged**
