### PR TITLE
Add text processors and accept free text in Android

### PR DESCRIPTION
**Pull request by monatis**
I implemented the text processors in Android except for the one to expand numbers. I couldn't find out a quick way to implement this functionality without either writing long loops and complicated conditionals, or adding 3rd party libraries as a dependency. What would you suggest for this?

Anyway, other text processors are working nicely, and so I updated UI to accept free text input from the user. If the edit box is empty, then it will inform them about it by speaking a default text.

### CODE REVIEW

**Comment by dathudeptrai** [comment]
@monatis I don't know how to do it easily. There are many problems about text normalization for every language. In my case, I use both writing long loops and complicated conditionals and adding 3rd party libraries as a dependency :)). In some cases, we can call normalization API in server and do synthesis in mobile devices :D. It's not EZ to bring full pipeline to mobile :D. Normalization is a very complex problem.

**Comment by monatis** [comment]
@dathudeptrai Ok I borrowed some magic from [here](https://rosettacode.org/wiki/Spelling_of_ordinal_numbers) and started to integrate it with some regex :D I'll commit into this

**Comment by monatis** [comment]
Hey @dathudeptrai number normalization is now complete and working 🚀

**Comment by dathudeptrai** [comment]
@monatis thanks very much, quick glance LGTM.

**Pull request merged**
