### PR TITLE
Load Speaker IDs mapping from Processor Mapper

### LINKED ISSUE #366: FastSpeech2 Speaker IDs do not correlate with the voice at inference
Hi,

I'm having some difficulties with inference on my FastSpeech2 model. I do not think the speaker IDs at inference correlate with those in `libritts_mapper.json`.

For example, my speakers_map says `"2999": 65`. Speaker 2999 is British male, but when doing inference with speaker_id 65, the voice is one of a Female American speaker instead.

```python
mel_before, mel_outputs, duration_outputs, _, _ = fastspeech2.inference(
    input_ids=tf.expand_dims(tf.convert_to_tensor(input_ids3, dtype=tf.int32), 0),
    speaker_ids=tf.convert_to_tensor([65], dtype=tf.int32),
    speed_ratios=tf.convert_to_tensor([1.5], dtype=tf.float32),
    f0_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32),
    energy_ratios =tf.convert_to_tensor([1.0], dtype=tf.float32)
)
```

My speakers_map says `"8382": 49`, Speaker 8382 is a British female, but when doing inference with speaker_id 49 I get an American Male

If I use my own speaker `"1": 50`, I get a British sounding female. The speaker is made from recordings of my own voice (male), so this is also incorrect.

I think somehow the speaker IDs are getting mixed up. Is this something you've seen before?

### PR DESCRIPTION
**Pull request by OscarVanL**
Kills two issues in one go!

This requires an extra argument to be provided when starting FastSpeech2 training from `examples/fastspeech2_libritts/train_fastspeech2.py`: `--dataset_mapping`, which gives the path to `libritts_mapper.json`. 
(Alternatively, all the arguments `energy-stat`, `dataset_stats`, `dataset_mapping`, can be combined into a single `stats-dump` argument, which points to the `dump` folder).

1. Speaker IDs at inference don't match those in `libritts_mapper.json` https://github.com/TensorSpeech/TensorFlowTTS/issues/366

2. Model does not raise an error if `n_speakers` (in fastspeech2's config) does not match the number of speakers in the dataset. https://github.com/TensorSpeech/TensorFlowTTS/issues/333

Please be aware I just made these changes and have not yet tested if it fixes #366 , give me a few hours and I'll be able to tell you if the speaker IDs at inference give the correct voice :D

### CODE REVIEW

**Comment by OscarVanL** [comment]
Is this what you were referring to? @machineko

**Comment by machineko** [comment]
> Is this what you were referring to? @machineko

Nope its still wrong u didnt change 

```python
        self.speakers = [
            self.speakers_map[i.split("_")[0]] for i in self.utt_ids
        ]  # TODO change but at the moment mfa folder name = speaker name
```
As u can see here this also need to be changed => https://github.com/TensorSpeech/TensorFlowTTS/blob/e5a5b87e4aa798c4a1197b11c222c4a1bf5ce819/examples/fastspeech2_libritts/fastspeech2_dataset.py#L152

**Comment by OscarVanL** [comment]
I'm not sure if that line needs to be changed.

utt_ids looks like `['100_121669_000003_000000', '100_121669_000004_000000', '100_121669_000004_000001', '100_121669_000005_000000', '100_121669_000005_000002', '100_121669_000008_000000', ...]`

So to find the correct speaker ID, surely this must be checked against the speaker map, which looks like this: `{"100": 0}`

So surely this code must be kept the same? Unless I am missing something?

**Comment by OscarVanL** [comment]
OK actually that change broke it, I think you cannot do this string function within the generator for some reason.

**Comment by machineko** [comment]
LGFM

**Review by machineko — APPROVED** [review]

**Review by dathudeptrai — APPROVED** [review]

**Comment by OscarVanL** [comment]
Thanks, although I was hoping you would squash the commits because the commit history is ugly 😅

**Pull request merged**
